---
# 1. PersistentVolumeClaim pour les données
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
# 2. Déploiement SonarQube
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      initContainers:
      # Initialisation des permissions (pour éviter les erreurs)
      - name: init-sonar
        image: busybox
        command: ['sh', '-c', 'chown -R 1000:1000 /opt/sonarqube/data']
        volumeMounts:
        - name: sonarqube-data
          mountPath: /opt/sonarqube/data
      containers:
      - name: sonarqube
        image: sonarqube:lts-community  # Version LTS plus stable
        ports:
        - containerPort: 9000
        env:
        # Configuration minimale mais fonctionnelle
        - name: SONAR_JDBC_URL
          value: "jdbc:h2:tcp://localhost:9092/sonar"
        - name: SONAR_JDBC_USERNAME
          value: "sonar"
        - name: SONAR_JDBC_PASSWORD
          value: "sonar"
        - name: SONAR_EMBEDDEDDATABASE_PORT
          value: "9092"
        # Réduction mémoire pour fonctionner sur Minikube
        - name: SONAR_WEB_JAVAOPTS
          value: "-Xmx512m -Xms128m -XX:MaxRAM=512m"
        - name: SONAR_SEARCH_JAVAOPTS
          value: "-Xmx256m -Xms128m -XX:MaxRAM=256m"
        - name: SONAR_ES_JAVA_OPTS
          value: "-Xms128m -Xmx128m"
        volumeMounts:
        - name: sonarqube-data
          mountPath: /opt/sonarqube/data
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "1.5Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api/system/status
            port: 9000
          initialDelaySeconds: 300  # 5 minutes pour le démarrage
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/system/status
            port: 9000
          initialDelaySeconds: 180  # 3 minutes
          periodSeconds: 20
      volumes:
      - name: sonarqube-data
        persistentVolumeClaim:
          claimName: sonarqube-data-pvc

---
# 3. Service NodePort
apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
spec:
  type: NodePort
  selector:
    app: sonarqube
  ports:
  - port: 9000
    targetPort: 9000
    nodePort: 30001
